//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bhsScandll.BHSDocUploadWebService2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://sg.bhsonline.us/bhsDocsUploadService1.asmx", ConfigurationName="BHSDocUploadWebService2.bhsDocsUploadService1Soap")]
    public interface bhsDocsUploadService1Soap {
        
        // CODEGEN: Generating message contract since element name TestResult from namespace https://sg.bhsonline.us/bhsDocsUploadService1.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://sg.bhsonline.us/bhsDocsUploadService1.asmx/Test", ReplyAction="*")]
        bhsScandll.BHSDocUploadWebService2.TestResponse Test(bhsScandll.BHSDocUploadWebService2.TestRequest request);
        
        // CODEGEN: Generating message contract since element name f from namespace https://sg.bhsonline.us/bhsDocsUploadService1.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://sg.bhsonline.us/bhsDocsUploadService1.asmx/UploadFile", ReplyAction="*")]
        bhsScandll.BHSDocUploadWebService2.UploadFileResponse UploadFile(bhsScandll.BHSDocUploadWebService2.UploadFileRequest request);
        
        // CODEGEN: Generating message contract since element name reqno from namespace https://sg.bhsonline.us/bhsDocsUploadService1.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://sg.bhsonline.us/bhsDocsUploadService1.asmx/FinalizeAllFiles", ReplyAction="*")]
        bhsScandll.BHSDocUploadWebService2.FinalizeAllFilesResponse FinalizeAllFiles(bhsScandll.BHSDocUploadWebService2.FinalizeAllFilesRequest request);
        
        // CODEGEN: Generating message contract since element name f from namespace https://sg.bhsonline.us/bhsDocsUploadService1.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://sg.bhsonline.us/bhsDocsUploadService1.asmx/SalixUploadFile", ReplyAction="*")]
        bhsScandll.BHSDocUploadWebService2.SalixUploadFileResponse SalixUploadFile(bhsScandll.BHSDocUploadWebService2.SalixUploadFileRequest request);
        
        // CODEGEN: Generating message contract since element name DocType from namespace https://sg.bhsonline.us/bhsDocsUploadService1.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://sg.bhsonline.us/bhsDocsUploadService1.asmx/SalixFinalizeAllFiles", ReplyAction="*")]
        bhsScandll.BHSDocUploadWebService2.SalixFinalizeAllFilesResponse SalixFinalizeAllFiles(bhsScandll.BHSDocUploadWebService2.SalixFinalizeAllFilesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test", Namespace="https://sg.bhsonline.us/bhsDocsUploadService1.asmx", Order=0)]
        public bhsScandll.BHSDocUploadWebService2.TestRequestBody Body;
        
        public TestRequest() {
        }
        
        public TestRequest(bhsScandll.BHSDocUploadWebService2.TestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestRequestBody {
        
        public TestRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResponse", Namespace="https://sg.bhsonline.us/bhsDocsUploadService1.asmx", Order=0)]
        public bhsScandll.BHSDocUploadWebService2.TestResponseBody Body;
        
        public TestResponse() {
        }
        
        public TestResponse(bhsScandll.BHSDocUploadWebService2.TestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://sg.bhsonline.us/bhsDocsUploadService1.asmx")]
    public partial class TestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestResult;
        
        public TestResponseBody() {
        }
        
        public TestResponseBody(string TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFile", Namespace="https://sg.bhsonline.us/bhsDocsUploadService1.asmx", Order=0)]
        public bhsScandll.BHSDocUploadWebService2.UploadFileRequestBody Body;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(bhsScandll.BHSDocUploadWebService2.UploadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://sg.bhsonline.us/bhsDocsUploadService1.asmx")]
    public partial class UploadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] f;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string doctype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string reqno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string releasecode;
        
        public UploadFileRequestBody() {
        }
        
        public UploadFileRequestBody(byte[] f, string doctype, string fileName, string reqno, string releasecode) {
            this.f = f;
            this.doctype = doctype;
            this.fileName = fileName;
            this.reqno = reqno;
            this.releasecode = releasecode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileResponse", Namespace="https://sg.bhsonline.us/bhsDocsUploadService1.asmx", Order=0)]
        public bhsScandll.BHSDocUploadWebService2.UploadFileResponseBody Body;
        
        public UploadFileResponse() {
        }
        
        public UploadFileResponse(bhsScandll.BHSDocUploadWebService2.UploadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://sg.bhsonline.us/bhsDocsUploadService1.asmx")]
    public partial class UploadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadFileResult;
        
        public UploadFileResponseBody() {
        }
        
        public UploadFileResponseBody(string UploadFileResult) {
            this.UploadFileResult = UploadFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinalizeAllFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FinalizeAllFiles", Namespace="https://sg.bhsonline.us/bhsDocsUploadService1.asmx", Order=0)]
        public bhsScandll.BHSDocUploadWebService2.FinalizeAllFilesRequestBody Body;
        
        public FinalizeAllFilesRequest() {
        }
        
        public FinalizeAllFilesRequest(bhsScandll.BHSDocUploadWebService2.FinalizeAllFilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://sg.bhsonline.us/bhsDocsUploadService1.asmx")]
    public partial class FinalizeAllFilesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string reqno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string releasecode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string _type;
        
        public FinalizeAllFilesRequestBody() {
        }
        
        public FinalizeAllFilesRequestBody(string reqno, string releasecode, string _type) {
            this.reqno = reqno;
            this.releasecode = releasecode;
            this._type = _type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinalizeAllFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FinalizeAllFilesResponse", Namespace="https://sg.bhsonline.us/bhsDocsUploadService1.asmx", Order=0)]
        public bhsScandll.BHSDocUploadWebService2.FinalizeAllFilesResponseBody Body;
        
        public FinalizeAllFilesResponse() {
        }
        
        public FinalizeAllFilesResponse(bhsScandll.BHSDocUploadWebService2.FinalizeAllFilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://sg.bhsonline.us/bhsDocsUploadService1.asmx")]
    public partial class FinalizeAllFilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FinalizeAllFilesResult;
        
        public FinalizeAllFilesResponseBody() {
        }
        
        public FinalizeAllFilesResponseBody(string FinalizeAllFilesResult) {
            this.FinalizeAllFilesResult = FinalizeAllFilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalixUploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalixUploadFile", Namespace="https://sg.bhsonline.us/bhsDocsUploadService1.asmx", Order=0)]
        public bhsScandll.BHSDocUploadWebService2.SalixUploadFileRequestBody Body;
        
        public SalixUploadFileRequest() {
        }
        
        public SalixUploadFileRequest(bhsScandll.BHSDocUploadWebService2.SalixUploadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://sg.bhsonline.us/bhsDocsUploadService1.asmx")]
    public partial class SalixUploadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] f;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string doctype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ReqType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int count;
        
        public SalixUploadFileRequestBody() {
        }
        
        public SalixUploadFileRequestBody(byte[] f, string doctype, string ReqType, string User, string Id, int count) {
            this.f = f;
            this.doctype = doctype;
            this.ReqType = ReqType;
            this.User = User;
            this.Id = Id;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalixUploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalixUploadFileResponse", Namespace="https://sg.bhsonline.us/bhsDocsUploadService1.asmx", Order=0)]
        public bhsScandll.BHSDocUploadWebService2.SalixUploadFileResponseBody Body;
        
        public SalixUploadFileResponse() {
        }
        
        public SalixUploadFileResponse(bhsScandll.BHSDocUploadWebService2.SalixUploadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://sg.bhsonline.us/bhsDocsUploadService1.asmx")]
    public partial class SalixUploadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SalixUploadFileResult;
        
        public SalixUploadFileResponseBody() {
        }
        
        public SalixUploadFileResponseBody(string SalixUploadFileResult) {
            this.SalixUploadFileResult = SalixUploadFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalixFinalizeAllFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalixFinalizeAllFiles", Namespace="https://sg.bhsonline.us/bhsDocsUploadService1.asmx", Order=0)]
        public bhsScandll.BHSDocUploadWebService2.SalixFinalizeAllFilesRequestBody Body;
        
        public SalixFinalizeAllFilesRequest() {
        }
        
        public SalixFinalizeAllFilesRequest(bhsScandll.BHSDocUploadWebService2.SalixFinalizeAllFilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://sg.bhsonline.us/bhsDocsUploadService1.asmx")]
    public partial class SalixFinalizeAllFilesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DocType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RequestType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Id;
        
        public SalixFinalizeAllFilesRequestBody() {
        }
        
        public SalixFinalizeAllFilesRequestBody(string DocType, string RequestType, string User, string Id) {
            this.DocType = DocType;
            this.RequestType = RequestType;
            this.User = User;
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalixFinalizeAllFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalixFinalizeAllFilesResponse", Namespace="https://sg.bhsonline.us/bhsDocsUploadService1.asmx", Order=0)]
        public bhsScandll.BHSDocUploadWebService2.SalixFinalizeAllFilesResponseBody Body;
        
        public SalixFinalizeAllFilesResponse() {
        }
        
        public SalixFinalizeAllFilesResponse(bhsScandll.BHSDocUploadWebService2.SalixFinalizeAllFilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://sg.bhsonline.us/bhsDocsUploadService1.asmx")]
    public partial class SalixFinalizeAllFilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SalixFinalizeAllFilesResult;
        
        public SalixFinalizeAllFilesResponseBody() {
        }
        
        public SalixFinalizeAllFilesResponseBody(string SalixFinalizeAllFilesResult) {
            this.SalixFinalizeAllFilesResult = SalixFinalizeAllFilesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface bhsDocsUploadService1SoapChannel : bhsScandll.BHSDocUploadWebService2.bhsDocsUploadService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class bhsDocsUploadService1SoapClient : System.ServiceModel.ClientBase<bhsScandll.BHSDocUploadWebService2.bhsDocsUploadService1Soap>, bhsScandll.BHSDocUploadWebService2.bhsDocsUploadService1Soap {
        
        public bhsDocsUploadService1SoapClient() {
        }
        
        public bhsDocsUploadService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public bhsDocsUploadService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public bhsDocsUploadService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public bhsDocsUploadService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bhsScandll.BHSDocUploadWebService2.TestResponse bhsScandll.BHSDocUploadWebService2.bhsDocsUploadService1Soap.Test(bhsScandll.BHSDocUploadWebService2.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public string Test() {
            bhsScandll.BHSDocUploadWebService2.TestRequest inValue = new bhsScandll.BHSDocUploadWebService2.TestRequest();
            inValue.Body = new bhsScandll.BHSDocUploadWebService2.TestRequestBody();
            bhsScandll.BHSDocUploadWebService2.TestResponse retVal = ((bhsScandll.BHSDocUploadWebService2.bhsDocsUploadService1Soap)(this)).Test(inValue);
            return retVal.Body.TestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bhsScandll.BHSDocUploadWebService2.UploadFileResponse bhsScandll.BHSDocUploadWebService2.bhsDocsUploadService1Soap.UploadFile(bhsScandll.BHSDocUploadWebService2.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public string UploadFile(byte[] f, string doctype, string fileName, string reqno, string releasecode) {
            bhsScandll.BHSDocUploadWebService2.UploadFileRequest inValue = new bhsScandll.BHSDocUploadWebService2.UploadFileRequest();
            inValue.Body = new bhsScandll.BHSDocUploadWebService2.UploadFileRequestBody();
            inValue.Body.f = f;
            inValue.Body.doctype = doctype;
            inValue.Body.fileName = fileName;
            inValue.Body.reqno = reqno;
            inValue.Body.releasecode = releasecode;
            bhsScandll.BHSDocUploadWebService2.UploadFileResponse retVal = ((bhsScandll.BHSDocUploadWebService2.bhsDocsUploadService1Soap)(this)).UploadFile(inValue);
            return retVal.Body.UploadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bhsScandll.BHSDocUploadWebService2.FinalizeAllFilesResponse bhsScandll.BHSDocUploadWebService2.bhsDocsUploadService1Soap.FinalizeAllFiles(bhsScandll.BHSDocUploadWebService2.FinalizeAllFilesRequest request) {
            return base.Channel.FinalizeAllFiles(request);
        }
        
        public string FinalizeAllFiles(string reqno, string releasecode, string _type) {
            bhsScandll.BHSDocUploadWebService2.FinalizeAllFilesRequest inValue = new bhsScandll.BHSDocUploadWebService2.FinalizeAllFilesRequest();
            inValue.Body = new bhsScandll.BHSDocUploadWebService2.FinalizeAllFilesRequestBody();
            inValue.Body.reqno = reqno;
            inValue.Body.releasecode = releasecode;
            inValue.Body._type = _type;
            bhsScandll.BHSDocUploadWebService2.FinalizeAllFilesResponse retVal = ((bhsScandll.BHSDocUploadWebService2.bhsDocsUploadService1Soap)(this)).FinalizeAllFiles(inValue);
            return retVal.Body.FinalizeAllFilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bhsScandll.BHSDocUploadWebService2.SalixUploadFileResponse bhsScandll.BHSDocUploadWebService2.bhsDocsUploadService1Soap.SalixUploadFile(bhsScandll.BHSDocUploadWebService2.SalixUploadFileRequest request) {
            return base.Channel.SalixUploadFile(request);
        }
        
        public string SalixUploadFile(byte[] f, string doctype, string ReqType, string User, string Id, int count) {
            bhsScandll.BHSDocUploadWebService2.SalixUploadFileRequest inValue = new bhsScandll.BHSDocUploadWebService2.SalixUploadFileRequest();
            inValue.Body = new bhsScandll.BHSDocUploadWebService2.SalixUploadFileRequestBody();
            inValue.Body.f = f;
            inValue.Body.doctype = doctype;
            inValue.Body.ReqType = ReqType;
            inValue.Body.User = User;
            inValue.Body.Id = Id;
            inValue.Body.count = count;
            bhsScandll.BHSDocUploadWebService2.SalixUploadFileResponse retVal = ((bhsScandll.BHSDocUploadWebService2.bhsDocsUploadService1Soap)(this)).SalixUploadFile(inValue);
            return retVal.Body.SalixUploadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bhsScandll.BHSDocUploadWebService2.SalixFinalizeAllFilesResponse bhsScandll.BHSDocUploadWebService2.bhsDocsUploadService1Soap.SalixFinalizeAllFiles(bhsScandll.BHSDocUploadWebService2.SalixFinalizeAllFilesRequest request) {
            return base.Channel.SalixFinalizeAllFiles(request);
        }
        
        public string SalixFinalizeAllFiles(string DocType, string RequestType, string User, string Id) {
            bhsScandll.BHSDocUploadWebService2.SalixFinalizeAllFilesRequest inValue = new bhsScandll.BHSDocUploadWebService2.SalixFinalizeAllFilesRequest();
            inValue.Body = new bhsScandll.BHSDocUploadWebService2.SalixFinalizeAllFilesRequestBody();
            inValue.Body.DocType = DocType;
            inValue.Body.RequestType = RequestType;
            inValue.Body.User = User;
            inValue.Body.Id = Id;
            bhsScandll.BHSDocUploadWebService2.SalixFinalizeAllFilesResponse retVal = ((bhsScandll.BHSDocUploadWebService2.bhsDocsUploadService1Soap)(this)).SalixFinalizeAllFiles(inValue);
            return retVal.Body.SalixFinalizeAllFilesResult;
        }
    }
}
